Provide a self-contained Maven project
Loom endpoints are currently broken with the following error:
java.lang.NullPointerException: Cannot invoke "java.lang.Thread$Builder.start(java.lang.Runnable)" because "this.threadBuilder" is null